name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: dependencies
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest